### ISSUE TITLE
Need your Proposal

### ISSUE THREAD

**Issue by L-Chris** [L-Chris/vue-design#1]
If you need some new feature or have proposal on the work, comment here.

**Comment by kevinaskin** [comment]
an error occured when I exit the program
it said
- **A JavaScript error occurred in the main process**
```
Uncaught Exception:
Error: Object has been destroyed
    at BrowserWindow.<anonymous> (/Applications/vue-design.app/Contents/Resources/app.asar/dist/electron/main.js:1:944)
    at emitOne (events.js:115:13)
    at BrowserWindow.emit (events.js:210:7)
    at EventEmitter.<anonymous> (/Applications/vue-design.app/Contents/Resources/app.asar/dist/electron/main.js:1:1172)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at WebContents.<anonymous> (/Applications/vue-design.app/Contents/Resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
```

**Comment by bajki** [comment]
Hi, how to reorder components, and how to drop component inside <section>.
Thanks,
Ivan
